config/routes.rb
Rails.application.routes.draw do


  get 'admins/show'
  devise_for :admins, controllers: {
        sessions: "admins/sessions",
        passwords: "admins/paswwords",
        registrations: "admins/registrations"
  }
  devise_for :users, controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  # devise_for :admins
  # devise_for :users

  # resources :admins


  root to: 'home#top' #ルートパス

  get "users/clip" => "users#clip"

  resources :users
  	resources :friendships, only: [:new, :create, :index, :destroy] do
  end

  resources :locations

  resources :messages, only: [:create, :show, :index, :edit, :update, :destroy]

  resources :rooms



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 同じmodelを参照する外部キーを一つのmodelでもつ方法
  # friendshipテーブルのfrom_user_idカラムまたはto_user_idカラムの値と同じidの値を持つユーザーを削除すると、friendshipテーブルのレコードも削除される
  has_many :from_user_transactions, class_name: 'Friendship', :foreign_key => 'from_user_id', dependent: :destroy
  has_many :to_user_transactions, class_name: 'Friendship', :foreign_key => 'to_user_id', dependent: :destroy

  has_many :locations, dependent: :destroy

  # 同じmodelを参照する外部キーを一つのmodelでもつ方法
  # roomテーブルのinvite_user_idカラムまたはinvited_user_idカラムの値と同じidの値を持つユーザーを削除すると、roomテーブルのレコードも削除される
  has_many :invite_user_transactions, class_name: 'Room', :foreign_key => 'invite_user_id', dependent: :destroy
  has_many :invited_user_transactions, class_name: 'Room', :foreign_key => 'invited_user_id', dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # user(=入力したフレンドIDを持つユーザー)とすでにフレンド関係にあるかの確認
  def is_friend?(user)
    Friendship.where(from_user_id: self.id, to_user_id: user.id).exists?
  end

  # user(=ユーザーページのユーザー)との間でチャットルームが存在するかの確認
  def is_made?(user)
    first_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: first_friendship.id).exists?
    second_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: second_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのto_user_idが一致する場合に、そのFriendshipのIDを持つルームチャットが存在するかの確認
  def is_made_first?(user)
    first_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: first_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのfrom_user_idが一致する場合に、そのFriendshipのIDを持つルームチャットが存在するかの確認
  def is_made_second?(user)
    second_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: second_friendship.id).exists?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  #ユーザーサインアップ後のリダイレクト先
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :friend_id, :email, :password, :deleted_at, :password_confirmation])
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  protected

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #ログアウト後のリダイレクト先
  def after_sign_out_path_for(resorce)
    root_path
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:clip, :show]

  def index
    if user_signed_in?
      @users = User.all
    else
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    if current_user.is_friend?(@user)
      @location = Location.where(user_id: @user.id)
      if @user.id == current_user.id
        @entries = current_user.entries
      else
        @room = Room.new
        @entry = Entry.new
      end
    elsif current_user.id == @user.id
      @location = Location.where(user_id: @user.id)
      if @user.id == current_user.id
        @entries = current_user.entries
      else
        @room = Room.new
        @entry = Entry.new
      end
    else
      flash[:alert] = "そのユーザーとはフレンドではないためそのページへは行けません"
      redirect_to user_path(current_user.id)
    end
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:alert] = "アカウントを削除しました"
    redirect_to root_path
  end

  def edit
  end

  def clip
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :friend_id, :email, :password, :deleted_at)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/clip.html.erb
<div class='user_clip' style="margin-top: 100px; text-align: center;">
  <h2>Clip</h2>
  <%= link_to "Clip location",new_location_path, class:"btn-lg btn-warning" %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class='user_index col-md-8 col-md-offset-2' style="margin-top: 100px;">
  <h2>ユーザー一覧</h2>
  <hr>
  <table class="table">
    <thead>
      <tr>
        <th>user name</th>
        <th>friend ID</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><a href="/users/<%= user.id %>"><%= user.user_name %></a></td>
          <td><%= user.friend_id %></td>
          <td><%= link_to "Show", user_path(user.id), class:"user_#{user.id}" %></td>
          <td><%= link_to "アカウント削除",user_path(user.id), "data-confirm" => "本当に消しますか?", method: :delete, class:"btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class='chat col-md-4' style="margin-top: 100px; text-align: center; margin-bottom: 50px;">
  <% if @user.id == current_user.id %>
    <div class="">
      <h2>チャット一覧</h2>
      <hr>
      <% @entries.each do |e| %>
        <p>
          <%= link_to room_path(e.room.id), class:"" do %>
            <strong><%= e.room.id %>   </strong>
          <% end %>
          <%= link_to "チャットルームを削除する", room_path(e.room.id), method: :delete, class:"btn-sm btn-danger" %>
        </p>
        <hr>
      <% end %>
      <%= link_to "チャット一覧を見る", rooms_path, class:"btn btn-info" %>
    </div>
  <% else %>
    <%= form_for @room do |f| %>
      <% @friendship = Friendship.find_by(from_user_id: current_user.id, to_user_id: @user.id) %>
      <%= f.hidden_field :friendship_id, :value => @friendship.id %>
      <%= f.hidden_field :invite_user_id, :value => current_user.id %>
      <%= f.hidden_field :invited_user_id, :value => @user.id %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, :value => @user.id %>
        <% end %>
      <%= f.submit "チャットを始める", class:"btn btn-warning" %>
    <% end %>
  <% end %>
</div>

<div class='user_show col-md-8' style="margin-top: 100px;">
<h2><span style="color: orange;"><%= @user.user_name %></span>のLocation一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th>location name</th>
        <th>location ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @location.each do |location| %>
        <% show_user = User.find(location.user_id) %>
        <tr>
          <td><%= location.location_name %></td>
          <td><%= location.id %></td>
          <td><%= link_to "Show", location_path(location.id) %></td>
          <td><%= link_to "削除", location_path(location.id), "data-confirm" => "本当に消しますか?", method: :delete, class:"btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>