config/routes.rb
Rails.application.routes.draw do


  get 'admins/show'
  devise_for :admins, controllers: {
        sessions: "admins/sessions",
        passwords: "admins/paswwords",
        registrations: "admins/registrations"
  }
  devise_for :users, controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  # devise_for :admins
  # devise_for :users

  # resources :admins


  root to: 'home#top' #ルートパス

  get "users/clip" => "users#clip"

  resources :users
  	resources :friendships, only: [:new, :create, :index, :destroy] do
  end

  resources :locations

  resources :messages, only: [:create, :show, :index, :edit, :update, :destroy]

  resources :rooms



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # 同じmodelを参照する外部キーを一つのmodelでもつ方法
  # friendshipテーブルのfrom_user_idカラムまたはto_user_idカラムの値と同じidの値を持つユーザーが削除されると、friendshipテーブルのレコードも削除される
  belongs_to :from_user, class_name: 'User', :foreign_key => 'from_user_id'
  belongs_to :to_user, class_name: 'User', :foreign_key => 'to_user_id'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
  	@friendship = Friendship.new
  end

  def create
	  friendship = Friendship.new(friendship_params)
	  to_friend_id = friendship.friend_id

  	if to_friend_id == current_user.friend_id
  	  @friendship = Friendship.new
        flash[:alert] = "それはあなたのフレンドIDです"
  	  render "new"
  	elsif
  	  to_user = User.find_by(friend_id: to_friend_id)

      if current_user.is_friend?(to_user)
        @friendship = Friendship.new
        flash[:alert] = to_user.user_name + "はすでにあなたのフレンドです"
	      render "new"
	    else
  	    friendship = Friendship.create(from_user_id: current_user.id, to_user_id: to_user.id, friend_id: to_user.friend_id)
  	    friendship_back = Friendship.create(from_user_id: to_user.id, to_user_id: current_user.id, friend_id: current_user.friend_id)
        flash[:notice] = to_user.user_name + "はあなたのフレンドになりました"
	      redirect_to friendships_path
	    end
	  else
  	  @friendship = Friendship.new
      flash[:alert] = "そのフレンドIDは存在しません"
  	  render "new"
	  end
  end

  def index
  	@friendship = Friendship.where(from_user_id: current_user.id)
  end

  def destroy
    friendship = Friendship.find(params[:id])
    to_user = User.find(friendship.to_user_id)
    friendship_back = Friendship.find_by(from_user_id: to_user.id, to_user_id: current_user.id)
    friendship.destroy
    friendship_back.destroy
    # フレンド関係を削除したときに、それに基づくチャットルームも削除する
    if Room.where(friendship_id: friendship.id).exists?
      first_room = Room.find_by(friendship_id: friendship.id)
      first_room.destroy
    else
      Room.where(friendship_id: friendship_back.id).exists?
      second_room = Room.find_by(friendship_id: friendship_back.id)
      second_room.destroy
    end
    flash[:notice] = to_user.user_name + "をフレンドから削除しました"
    redirect_to friendships_path
  end

  private
    def friendship_params
      params.require(:friendship).permit(:from_user_id, :to_user_id, :friend_id)
    end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<div class='friendships_index col-md-8 col-md-offset-2' style="margin-top: 100px;">
  <h2 class='friendships_index col-md-8'><span style="color: orange;"><%= current_user.user_name %></span>のフレンド一覧</h2>
  <h2 class='friendships_index col-md-4' style="float: right;">
    <div style="float: right;">
      <%= link_to '友達追加', new_friendship_path, class:"glyphicon glyphicon-user btn-lg btn-info" %>
    </div>
  </h2>
  <table class="table">
    <thead>
      <tr>
        <th>フレンド</th>
        <th>フレンドID</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @friendship.each do |friendship| %>
        <% to_user = User.find(friendship.to_user_id) %>
        <tr>
          <td><%= to_user.user_name %></td>
          <td><%= to_user.friend_id %></td>
          <td><%= link_to "Show", user_path(to_user) %></td>
          <td><%= link_to "解除", friendship_path(friendship.id), "data-confirm" => "本当に消しますか?", method: :delete, class:"btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/friendships/new.html.erb
<h1 style="text-align: center; margin-top: 100px; margin-bottom: 40px;">Invite friend!!</h1>
  <%= form_for(@friendship) do |f| %>
    <div class="field row col-xs-4 col-xs-offset-4">
      <%= f.label :フレンドID %>
      <%= f.text_field :friend_id, class:"col-xs-12 book_title" %>
    </div>
    <div class="actions row col-xs-4 col-xs-offset-4">
      <%= f.submit 'Invite', class:"btn btn-primary col-xs-12" %>
    </div>
  <% end %>