config/routes.rb
Rails.application.routes.draw do


  get 'admins/show'
  devise_for :admins, controllers: {
        sessions: "admins/sessions",
        passwords: "admins/paswwords",
        registrations: "admins/registrations"
  }
  devise_for :users, controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  # devise_for :admins
  # devise_for :users

  # resources :admins


  root to: 'home#top' #ルートパス

  get "users/clip" => "users#clip"

  resources :users
  	resources :friendships, only: [:new, :create, :index, :destroy] do
  end

  resources :locations

  resources :messages, only: [:create, :show, :index, :edit, :update, :destroy]

  resources :rooms



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <h3 style="margin-top: 13px; margin-bottom: 14px;"><span>test</span></h3>
        </nav>
          <% if user_signed_in? %>
            <nav class='nav navbar-nav' >
              <h4 style="margin-top: 19px; margin-bottom: 14px; margin-left: 50px; color: orange;"><span><%= current_user.user_name %> ID <%= current_user.id %></span></h4>
            </nav>
          <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to " Mypage", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to " Clip", users_clip_path, class: "glyphicon glyphicon-clip clip" %></li>
              <li><%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users" %></li>
              <li><%= link_to ' Friends', friendships_path, class: "glyphicon glyphicon-user friends" %></li>
              <li><%= link_to " Invite!!", new_friendship_path, class: "glyphicon glyphicon-user invite" %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
            <% elsif admin_signed_in? %>
              <li class='nav navbar-nav'  style="margin-top: 17px; margin-bottom: 14px;">管理者</li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-block" %></li>
            <% else %>
              <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if notice %>
      <br>
      <p class="alert alert-success" style="text-align: center;" ><%= notice %></p>
    <% end %>
    <% if alert %>
      <br>
      <p class="alert alert-danger" style="text-align: center;" ><%= alert %></p>
    <% end %>

    <div class='body'>
      <div class='container'>
        <div class='row'>

          <%= yield %>

        </div>
      </div>
    </div>

  </body>
</html>